CREATE PROCEDURE [templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].[test IsMissing column set to 1]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].ACTUAL') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].ACTUAL;
	IF OBJECT_ID('[templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].EXPECTED') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].EXPECTED;

	EXECUTE tSQLt.FakeTable @TableName = '[dimensionSchema].[templateDimCoreName_Dim]';
	
	--ACT
	DECLARE @SK INT = -2;
	DECLARE @NK INT = -2;
	DECLARE @MissingString VARCHAR(500) = 'MissingString';
	EXECUTE [templateSchema].[templateDimCoreName_dimSetup_Idempotent_MissingMember_usp] @MissingMemberString = @MissingString, @MissingMemberSK = @SK, @MissingMemberNK = @NK;

	SELECT 
	 [d].[templateDimCoreName_IsMissing]
	INTO [templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].ACTUAL
	FROM [dimensionSchema].[templateDimCoreName_Dim] d;

	--ASSERT
	CREATE TABLE [templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].EXPECTED (
		 [templateDimCoreName_IsMissing] BIT NOT NULL
	);
	INSERT INTO [templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].EXPECTED (
		 [templateDimCoreName_IsMissing]
	) VALUES (
		 1
	);

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].EXPECTED'
,@Actual = '[templateSchema__templateDimCoreName_dimSetup_Idempotent_MissingMember_usp].ACTUAL';

END

/****
Script generated by cookiecutter
,for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
