CREATE PROCEDURE [templateSchema__templateDimCoreName_predim_orchestration_usp].[test clearTables does NOT fire if stg is not a table]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_orchestration_usp].ACTUAL') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_orchestration_usp].ACTUAL;
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_orchestration_usp].EXPECTED') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_orchestration_usp].EXPECTED;

	EXECUTE tSQLt.SpyProcedure @ProcedureName = '[templateSchema].[templateDimCoreName_predim_setup_clearTables_usp]';
	EXECUTE tSQLt.SpyProcedure @ProcedureName = '[templateSchema].[templateDimCoreName_predim_Step1_copycurrent_usp]';
	EXECUTE tSQLt.SpyProcedure @ProcedureName = '[templateSchema].[templateDimCoreName_predim_Step2_prep_usp]';
	EXECUTE tSQLt.SpyProcedure @ProcedureName = '[templateSchema].[templateDimCoreName_predim_Step3_prep_updateSCDStatus_usp]';
	EXECUTE tSQLt.SpyProcedure @ProcedureName = '[templateSchema].[templateDimCoreName_predim_Step4_prep_DeleteIgnorable]';
	DROP TABLE [StagingSchema].[templateDimCoreName_dimSrc_stg];
	DECLARE @Expected INT = 0;
	
	--ACT
	EXECUTE [templateSchema].[templateDimCoreName_predim_orchestration_usp];

	--ASSERT
	DECLARE @Actual INT = NULL;
	SELECT @Actual = COUNT(1) FROM [templateSchema].[templateDimCoreName_predim_setup_clearTables_usp_SpyProcedureLog];

	EXECUTE [tSQLt].AssertEquals @Expected = @Expected, @Actual = @Actual;

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
