CREATE PROCEDURE [templateSchema__templateDimCoreName_predim_orchestration_usp].[test No PENDING rows after execution]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_orchestration_usp].ACTUAL') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_orchestration_usp].ACTUAL;
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_orchestration_usp].EXPECTED') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_orchestration_usp].EXPECTED;

	/*Deactivate the clear-table sproc*/
	EXECUTE tSQLt.SpyProcedure @ProcedureName = '[templateSchema].[templateDimCoreName_predim_setup_clearTables_usp]', @CommandToExecute = 'SELECT 1'

	EXECUTE tSQLt.FakeTable @TableName = '[templateSchema].[Dim_templateDimCoreName]';

	EXECUTE TestHelpers.DataBuilder_templateSchema_Dim_templateDimCoreName @SK_templateDimCoreName = 1, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 1, @SampleColumnOne_Cur = '2', @SampleColumnTwo_Cur = '1', @Ctl_CurrentFlag = 0;
	EXECUTE TestHelpers.DataBuilder_templateSchema_Dim_templateDimCoreName @SK_templateDimCoreName = 2, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 1, @SampleColumnOne_Cur = '1', @SampleColumnTwo_Cur = '1', @Ctl_CurrentFlag = 1;
	EXECUTE TestHelpers.DataBuilder_templateSchema_Dim_templateDimCoreName @SK_templateDimCoreName = 3, @NK_SourceSystemID1 = 2, @NK_SourceSystemID2 = 2, @SampleColumnOne_Cur = '2', @SampleColumnTwo_Cur = '2', @Ctl_CurrentFlag = 1;

	/*Unchanged*/
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_dimSrc_stg @NK_SourceSystemID1 = 2, @NK_SourceSystemID2 = 2, @SampleColumnOne = '2', @SampleColumnTwo = '2', @Ctl_EffectiveDate = '2000-01-01';
	/*New*/
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_dimSrc_stg @NK_SourceSystemID1 = 3, @NK_SourceSystemID2 = 3, @SampleColumnOne = 'Fred', @SampleColumnTwo = '2', @Ctl_EffectiveDate = '2000-01-01';
	/*Updated*/
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_dimSrc_stg @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 1, @SampleColumnOne = 'Fred', @SampleColumnTwo = '1', @Ctl_EffectiveDate = '2000-01-01';


	--ACT
	EXECUTE [templateSchema].[templateDimCoreName_predim_orchestration_usp];
	
	SELECT 
	 [NK_SourceSystemID1]
	,[NK_SourceSystemID2]
	,[SCD_Status]
	INTO [templateSchema__templateDimCoreName_predim_orchestration_usp].ACTUAL
	FROM [templateSchema].[templateDimCoreName_predim_prep];
	
	--ASSERT
	CREATE TABLE [templateSchema__templateDimCoreName_predim_orchestration_usp].EXPECTED (
		 [NK_SourceSystemID1] INT
		,[NK_SourceSystemID2] INT
		,[SCD_Status] VARCHAR(30)
	);
	INSERT INTO [templateSchema__templateDimCoreName_predim_orchestration_usp].EXPECTED (
		 [NK_SourceSystemID1]
		,[NK_SourceSystemID2]
		,[SCD_Status]
	) VALUES (3,3,'NEW')
		,(1,1,'UPDATE')
	;

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[templateSchema__templateDimCoreName_predim_orchestration_usp].EXPECTED', @Actual = '[templateSchema__templateDimCoreName_predim_orchestration_usp].ACTUAL';

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
