CREATE PROCEDURE [templateSchema__templateDimCoreName_Predim_ControlFlow_IsStgATable].[test Returns 1 if stg is a table]
AS
BEGIN
	--ASSEMBLE
	DECLARE @Expected BIT = 1;
	
	--ACT
	DECLARE @Actual BIT;
	EXECUTE @Actual = [templateSchema].[templateDimCoreName_Predim_ControlFlow_IsStgATable_usp];
	
	--ASSERT
	EXECUTE [tSQLt].AssertEquals @Expected = @Expected, @Actual = @Actual;

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
