CREATE PROCEDURE [templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].[test Join Filters Correctly]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].ACTUAL') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].ACTUAL;
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].EXPECTED') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].EXPECTED;

	EXECUTE tSQLt.FakeTable @TableName = '[templateSchema].templateDimCoreName_dimSrc_stg';
	EXECUTE tSQLt.FakeTable @TableName = '[templateSchema].Dim_templateDimCoreName';
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_dimSrc_stg @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 1;
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_dimSrc_stg @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 2;

	/*NOTE! For on set of Natural Keys, the Supernatural Key would be the same. But for testing, this allows us to identify which row we are getting back.*/
	EXECUTE TestHelpers.DataBuilder_templateSchema_Dim_templateDimCoreName @SNK_templateDimCoreName = 2, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 2, @Ctl_CurrentFlag = 1;
	EXECUTE TestHelpers.DataBuilder_templateSchema_Dim_templateDimCoreName @SNK_templateDimCoreName = 3, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 2, @Ctl_CurrentFlag = 0;
	EXECUTE TestHelpers.DataBuilder_templateSchema_Dim_templateDimCoreName @SNK_templateDimCoreName = 3, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 2, @Ctl_CurrentFlag = 0;

	--ACT
	SELECT 
	 [dim__SNK_templateDimCoreName]
	,[NK_SourceSystemID1]
	,[NK_SourceSystemID2]
	INTO [templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].ACTUAL
	FROM [templateSchema].[templateDimCoreName_predim_Step2_prep_corejoin_vw];

	--ASSERT
	CREATE TABLE [templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].EXPECTED (
		 [dim__SNK_templateDimCoreName] bigint
		,[NK_SourceSystemID1] int
		,[NK_SourceSystemID2] int
	);
	INSERT INTO [templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].EXPECTED (
		 dim__SNK_templateDimCoreName
		,NK_SourceSystemID1
		,NK_SourceSystemID2
	) VALUES
		/*New Natural Keys*/
		(NULL, 1, 1)
		/*Known Natural Keys*/
		,(2,1,2);

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].EXPECTED', @Actual = '[templateSchema__templateDimCoreName_predim_Step2_prep_corejoin_vw].ACTUAL';

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
