CREATE PROCEDURE [templateSchema__templateDimCoreName_orchestration_usp].[test Dim T1 Load Part 2]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[templateSchema__templateDimCoreName_orchestration_usp].ACTUAL') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_orchestration_usp].ACTUAL;
	IF OBJECT_ID('[templateSchema__templateDimCoreName_orchestration_usp].EXPECTED') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_orchestration_usp].EXPECTED;

	DECLARE @Date1 DATETIME2 = '1999-12-31';
	DECLARE @Date2 DATETIME2 = '2000-01-01';
	DECLARE @Date3 DATETIME2 = '2000-01-02';
	EXECUTE TestHelpers.[DataBuilder_StagingSchema_templateDimCoreName_dimSrc_stg] @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 11, @SampleColumnOne = 'Fred', @SampleColumnTwo = '1', @Ctl_EffectiveDate = @Date1;
	EXECUTE TestHelpers.[DataBuilder_StagingSchema_templateDimCoreName_dimSrc_stg] @NK_SourceSystemID1 = 2, @NK_SourceSystemID2 = 22, @SampleColumnOne = '2', @SampleColumnTwo = '2', @Ctl_EffectiveDate = @Date1;

	EXECUTE [templateSchema].[templateDimCoreName_orchestration_usp];
	
	DELETE [StagingSchema].[templateDimCoreName_dimSrc_stg];
	/*Update*/
	EXECUTE TestHelpers.[DataBuilder_StagingSchema_templateDimCoreName_dimSrc_stg] @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 11, @SampleColumnOne = 'FredPrime', @SampleColumnTwo = '1', @Ctl_EffectiveDate = @Date2;
	/*Unchanged*/
	EXECUTE TestHelpers.[DataBuilder_StagingSchema_templateDimCoreName_dimSrc_stg] @NK_SourceSystemID1 = 2, @NK_SourceSystemID2 = 22, @SampleColumnOne = '2', @SampleColumnTwo = '2', @Ctl_EffectiveDate = @Date2;
	/*New*/
	EXECUTE TestHelpers.[DataBuilder_StagingSchema_templateDimCoreName_dimSrc_stg] @NK_SourceSystemID1 = 3, @NK_SourceSystemID2 = 33, @SampleColumnOne = 'Fred', @SampleColumnTwo = '2', @Ctl_EffectiveDate = @Date2;

	--ACT
	EXECUTE [templateSchema].[templateDimCoreName_orchestration_usp];

	SELECT 
	 [NK_SourceSystemID1]
	,[NK_SourceSystemID2]
	,[SampleColumnOne_Cur]
	,[SampleColumnTwo_Cur]
	,[templateDimCoreName_IsMissing]
	INTO [templateSchema__templateDimCoreName_orchestration_usp].ACTUAL
	FROM [dimensionSchema].[templateDimCoreName_T1_dim];

	--ASSERT
	CREATE TABLE [templateSchema__templateDimCoreName_orchestration_usp].EXPECTED (
		 [NK_SourceSystemID1] NVARCHAR(500) NOT NULL /*Natural Key*/
		,[NK_SourceSystemID2] NVARCHAR(500) NOT NULL /*Natural Key*/
		,[SampleColumnOne_Cur] VARCHAR(500) NOT NULL
		,[SampleColumnTwo_Cur] VARCHAR(500) NOT NULL
		,[templateDimCoreName_IsMissing] BIT NOT NULL
	);
	INSERT INTO [templateSchema__templateDimCoreName_orchestration_usp].EXPECTED (
		 [NK_SourceSystemID1]
		,[NK_SourceSystemID2]
		,[SampleColumnOne_Cur]
		,[SampleColumnTwo_Cur]
		,[templateDimCoreName_IsMissing]
	)
	SELECT
		 [NK_SourceSystemID1]
		,[NK_SourceSystemID2]
		,[SampleColumnOne_Cur]
		,[SampleColumnTwo_Cur]
		,[templateDimCoreName_IsMissing]
	FROM (VALUES (
		 1		--[NK_SourceSystemID1]
		,11		--[NK_SourceSystemID2]
		,'FredPrime'		--[SampleColumnOne_Cur]
		,'1'		--[SampleColumnTwo_Cur]
		,0		--[templateDimCoreName_IsMissing]
	),(
		 2		--[NK_SourceSystemID1]
		,22		--[NK_SourceSystemID2]
		,'2'		--[SampleColumnOne_Cur]
		,'2'		--[SampleColumnTwo_Cur]
		,0		--[templateDimCoreName_IsMissing]
	),(
		 3		--[NK_SourceSystemID1]
		,33		--[NK_SourceSystemID2]
		,'Fred'		--[SampleColumnOne_Cur]
		,'2'		--[SampleColumnTwo_Cur]
		,0		--[templateDimCoreName_IsMissing]
	),(
		 -1		--[NK_SourceSystemID1]
		,-1		--[NK_SourceSystemID2]
		,'Context Not Specified'		--[SampleColumnOne_Cur]
		,'Context Not Specified'		--[SampleColumnTwo_Cur]
		,1		--[templateDimCoreName_IsMissing]
	) ) AS a (
		 [NK_SourceSystemID1]
		,[NK_SourceSystemID2]
		,[SampleColumnOne_Cur]
		,[SampleColumnTwo_Cur]
		,[templateDimCoreName_IsMissing]
	)
	;

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[templateSchema__templateDimCoreName_orchestration_usp].EXPECTED', @Actual = '[templateSchema__templateDimCoreName_orchestration_usp].ACTUAL';

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
