CREATE PROCEDURE [templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].[test Where Clause]
AS
BEGIN
	--ASSEMBLE
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].ACTUAL') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].ACTUAL;
	IF OBJECT_ID('[templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].EXPECTED') IS NOT NULL DROP TABLE [templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].EXPECTED;

	EXECUTE tSQLt.FakeTable @TableName = '[templateSchema].templateDimCoreName_predim_prep';
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_predim_prep @SCD_Status = 'PENDING';
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_predim_prep @SCD_Status = 'NEW';
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_predim_prep @SCD_Status = 'UPDATE';
	EXECUTE TestHelpers.DataBuilder_templateSchema_templateDimCoreName_predim_prep @SCD_Status = 'IGNORE';

	--ACT
	EXECUTE [templateSchema].[templateDimCoreName_predim_Step4_prep_DeleteIgnorable];

	SELECT 
	[SCD_Status]
	INTO [templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].ACTUAL
	FROM [templateSchema].[templateDimCoreName_predim_prep];

	--ASSERT
	CREATE TABLE [templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].EXPECTED (
		[SCD_Status] VARCHAR(30)
	);
	INSERT INTO [templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].EXPECTED (
		[SCD_Status]
	) VALUES ('PENDING'),('NEW'),('UPDATE');

	EXECUTE [tSQLt].AssertEqualsTable @Expected = '[templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].EXPECTED', @Actual = '[templateSchema__templateDimCoreName_predim_Step4_prep_DeleteIgnorable].ACTUAL';

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
