CREATE PROCEDURE [dimensionSchema__templateDimCoreName_DimSKLookup_usvf].[test NULL NKs Get Missing SK]
AS
BEGIN
	--ASSEMBLE
	EXECUTE tSQLt.FakeTable @TableName = '[dimensionSchema].[templateDimCoreName_Dim]';
	EXECUTE [TestHelpers].[DataBuilder_dimensionSchema_templateDimCoreName_Dim] @SK_templateDimCoreName = 1, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 1, @Ctl_CurrentFlag = 1, @Ctl_EffectiveDate = '1900-01-01', @Ctl_EndDate_Excl = '2000-01-01';
	EXECUTE [TestHelpers].[DataBuilder_dimensionSchema_templateDimCoreName_Dim] @SK_templateDimCoreName = 2, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 1, @Ctl_CurrentFlag = 1, @Ctl_EffectiveDate = '2000-01-01', @Ctl_EndDate_Excl = '2000-12-31';
	EXECUTE [TestHelpers].[DataBuilder_dimensionSchema_templateDimCoreName_Dim] @SK_templateDimCoreName = 3, @NK_SourceSystemID1 = 1, @NK_SourceSystemID2 = 1, @Ctl_CurrentFlag = 1, @Ctl_EffectiveDate = '2000-12-31', @Ctl_EndDate_Excl = '9999-12-31';
	DECLARE @Expected INT = -1;

	--ACT
	DECLARE @Actual INT = NULL;
	SET @Actual = [dimensionSchema].[templateDimCoreName_DimSKLookup_usvf](NULL,NULL,'2000-01-01',default);

	--ASSERT

	EXECUTE [tSQLt].AssertEquals @Expected = @Expected, @Actual = @Actual;

END

/****
Script generated by cookiecutter, for completion by user.
https://github.com/sdoubleday/cookiecutter-tsqlt-class-vs
This test compares the contents of EXPECTED and ACTUAL.
****/
/****
Suggestion: Verify the object being selected from in the
Act section. It defaults to your object under test.
****/
